// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "node:path";
import { defineConfig } from "prisma/config";

config({ path: resolve(process.cwd(), ".env.local") });
config({ path: resolve(process.cwd(), ".env") });

// Prisma CLI (migrate, db push) uses a direct connection — not the pooled app URL.
const migrationUrl =
  process.env["DATABASE_URL_UNPOOLED"] ??
  process.env["DIRECT_URL"] ??
  process.env["DATABASE_URL"] ??
  "";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: migrationUrl,
  },
});
